
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-reader
rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - events
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-reader-binding
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: default
roleRef:
  kind: ClusterRole
  name: fluent-bit-reader
  apiGroup: rbac.authorization.k8s.io