apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
spec:
  template:
    spec:
      containers:
        resources:
          requests:
            memory: 756mi
            cpu: "0.1"
          limits:
            memory: 756Mi
            cpu: "2"